"use client"

import { useState } from "react"
import {
  Mail,
  FileText,
  CalendarDays,
  ShoppingBag,
  Pill,
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  ArrowLeft,
  Clock,
} from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog"

const defaultMedications = [
  { name: "N/A", type: "N/A", purpose: "N/A", dosage: "N/A", status: "safe" as const },
  { name: "N/A", type: "N/A", purpose: "N/A", dosage: "N/A", status: "safe" as const },
  { name: "N/A", type: "N/A", purpose: "N/A", dosage: "N/A", status: "safe" as const },
]

const interactionResults = [
  {
    pair: "Metformin + Lisinopril",
    severity: "none",
    note: "No known interaction. Safe to take together.",
  },
  {
    pair: "Metformin + Atorvastatin",
    severity: "none",
    note: "No known interaction. Safe to take together.",
  },
  {
    pair: "Lisinopril + Atorvastatin",
    severity: "mild",
    note: "Minor: Both may affect kidney function. Monitor with regular blood work.",
  },
]

const schedule = [
  { time: "8:00 AM", medications: ["Metformin 500mg", "Lisinopril 10mg"], meal: "With breakfast" },
  { time: "6:00 PM", medications: ["Metformin 500mg"], meal: "With dinner" },
  { time: "10:00 PM", medications: ["Atorvastatin 20mg"], meal: "Before bed" },
]

export function SummaryDashboard({ onBack, summary }: { onBack: () => void; summary?: any }) {
  const [phoneDialogOpen, setPhoneDialogOpen] = useState(false)
  const [phoneNumber, setPhoneNumber] = useState("")
  const [deploying, setDeploying] = useState(false)
  const [deployed, setDeployed] = useState(false)
  const [deployError, setDeployError] = useState<string | null>(null)

  // runtime-provided summary (from SessionView) overrides static content when present
  const runtimeMeds = summary?.medications || null
  const runtimeSummaryRaw = summary?.aiSummary || summary?.summaryText || null
  const runtimeTranscript = summary?.transcript || null

  // Normalize summary into clean bullet strings regardless of format
  const summaryBullets: string[] = (() => {
    let src = runtimeSummaryRaw
    if (!src) return []
    // If object/array, extract the useful part
    if (typeof src === 'object') {
      if (Array.isArray(src)) {
        src = src.join('\n')
      } else if (src.summary) {
        src = Array.isArray(src.summary) ? src.summary.join('\n') : String(src.summary)
      } else {
        src = JSON.stringify(src)
      }
    }
    // Try parsing as JSON string
    if (typeof src === 'string') {
      try {
        const parsed = JSON.parse(src)
        if (Array.isArray(parsed)) {
          src = parsed.join('\n')
        } else if (parsed?.summary) {
          src = Array.isArray(parsed.summary) ? parsed.summary.join('\n') : String(parsed.summary)
        }
      } catch (_) { /* not JSON, use as-is */ }
    }
    return String(src)
      .split(/\n|•/)
      .map((l: string) => l.replace(/^[\-\s"]+|["]+$/g, '').trim())
      .filter((l: string) => l.length > 0)
  })()

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-background/80 backdrop-blur-md border-b border-border">
        <div className="flex items-center justify-between px-6 py-4 max-w-5xl mx-auto">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
          >
            <ArrowLeft className="size-4" />
            New Session
          </button>
          <h1 className="text-sm font-semibold text-foreground">
            Session Summary
          </h1>
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Clock className="size-3.5" />
            <span>Feb 28, 2026</span>
          </div>
        </div>
      </header>

      <main className="px-6 py-8 max-w-5xl mx-auto flex flex-col gap-8">
        {/* AI Disclaimer */}
        <div className="flex items-start gap-3 p-4 rounded-xl border border-border bg-warning/10">
          <AlertTriangle className="size-5 text-warning-foreground flex-shrink-0 mt-0.5" />
          <p className="text-sm text-warning-foreground leading-relaxed">
            This summary was generated by an AI assistant and has not been reviewed by a medical professional. Always consult your doctor before making changes to your medication regimen.
          </p>
        </div>

        {/* Overall Summary (runtime) or fallback status */}
        {summaryBullets.length > 0 ? (
          <div className="flex flex-col items-start gap-3 p-6 rounded-2xl bg-card border border-border">
            <h2 className="text-lg font-semibold text-foreground">Session Summary</h2>
            <ul className="flex flex-col gap-2.5 w-full">
              {summaryBullets.map((line: string, i: number) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-muted-foreground leading-relaxed">
                    <span className="mt-1 size-1.5 rounded-full bg-primary flex-shrink-0" />
                    {line}
                  </li>
                ))}
            </ul>
            {runtimeTranscript && runtimeTranscript.length > 0 && (
              <details className="mt-2 text-xs text-muted-foreground">
                <summary className="cursor-pointer">View transcript ({runtimeTranscript.length} lines)</summary>
                <div className="mt-2">
                  {runtimeTranscript.map((t: any, i: number) => (
                    <p key={i} className="text-xs py-1 border-b border-border">
                      <strong className="uppercase text-[10px] tracking-wider mr-2">{t.speaker}</strong>
                      {t.text}
                    </p>
                  ))}
                </div>
              </details>
            )}
            <DeployVoiceAgentButton deployed={deployed} onClick={() => { if (!deployed) setPhoneDialogOpen(true) }} />
          </div>
        ) : (
          <div className="flex flex-col items-center gap-3 p-8 rounded-2xl bg-primary/5 border border-primary/20">
            <div className="flex items-center justify-center size-16 rounded-full bg-primary/10">
              <ShieldCheck className="size-8 text-primary" />
            </div>
            <h2 className="text-xl font-bold text-foreground">
              No Critical Interactions Found
            </h2>
            <p className="text-sm text-muted-foreground text-center max-w-md">
              All 3 detected medications have been cross-checked against FDA databases. One minor note was flagged for your awareness.
            </p>
            <DeployVoiceAgentButton deployed={deployed} onClick={() => { if (!deployed) setPhoneDialogOpen(true) }} />
          </div>
        )}

        {/* Detected Medications */}
        <section className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <Pill className="size-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Detected Medications
            </h2>
          </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {(runtimeMeds ?? defaultMedications).map((med: any) => (
              <div
                key={med.name || med.label || String(med)}
                className="flex flex-col gap-3 p-5 rounded-xl border border-border bg-card"
              >
                <div className="flex items-start justify-between">
                  <div className="flex flex-col gap-1">
                    <h3 className="font-semibold text-foreground text-sm">
                      {med.name}
                    </h3>
                    <span className="text-xs text-muted-foreground">
                      {med.type || ''}
                    </span>
                  </div>
                  {med.status === "safe" ? (
                    <CheckCircle2 className="size-5 text-success flex-shrink-0" />
                  ) : (
                    <AlertTriangle className="size-5 text-warning flex-shrink-0" />
                  )}
                </div>
                <div className="flex flex-col gap-1.5 text-xs text-muted-foreground">
                  <div className="flex items-center justify-between">
                    <span>Purpose</span>
                    <span className="text-foreground font-medium">{med.purpose}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Dosage</span>
                    <span className="text-foreground font-medium">{med.dosage}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Interaction Check */}
        <section className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <ShieldCheck className="size-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Interaction Check
            </h2>
          </div>
          <div className="flex flex-col gap-3">
            {interactionResults.map((result) => (
              <div
                key={result.pair}
                className="flex items-start gap-4 p-4 rounded-xl border border-border bg-card"
              >
                <div className="flex-shrink-0 mt-0.5">
                  {result.severity === "none" ? (
                    <CheckCircle2 className="size-5 text-success" />
                  ) : (
                    <AlertTriangle className="size-5 text-warning" />
                  )}
                </div>
                <div className="flex flex-col gap-1">
                  <h3 className="text-sm font-semibold text-foreground">
                    {result.pair}
                  </h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {result.note}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Medication Schedule */}
        <section className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <Clock className="size-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Recommended Schedule
            </h2>
          </div>
          <div className="flex flex-col gap-3">
            {schedule.map((slot) => (
              <div
                key={slot.time}
                className="flex items-center gap-5 p-4 rounded-xl border border-border bg-card"
              >
                <div className="flex flex-col items-center gap-0.5 min-w-[72px]">
                  <span className="text-base font-bold text-foreground">
                    {slot.time}
                  </span>
                  <span className="text-[10px] text-muted-foreground uppercase tracking-wider">
                    {slot.meal}
                  </span>
                </div>
                <div className="h-8 w-px bg-border" />
                <div className="flex flex-wrap gap-2">
                  {slot.medications.map((med) => (
                    <span
                      key={med}
                      className="px-3 py-1.5 rounded-lg bg-primary/10 text-primary text-xs font-medium"
                    >
                      {med}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Post-Session Actions */}
        <section className="flex flex-col gap-4">
          <h2 className="text-lg font-semibold text-foreground">
            Quick Actions
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <ActionCard
              icon={<Mail className="size-5" />}
              title="View Doctor's Draft"
              description="Open the prepared email summary for your physician"
            />
            <ActionCard
              icon={<FileText className="size-5" />}
              title="Share Schedule"
              description="Share the medication schedule as a Google Doc"
            />
            <ActionCard
              icon={<CalendarDays className="size-5" />}
              title="Add to Calendar"
              description="Sync dosage times to your Google Calendar"
            />
            <ActionCard
              icon={<ShoppingBag className="size-5" />}
              title="Order Refill"
              description="Connect to your pharmacy portal for refills"
              disabled
            />
          </div>
        </section>

        {/* Deploy Gemini Voice Agent Dialog */}
        <Dialog open={phoneDialogOpen} onOpenChange={setPhoneDialogOpen}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle>Deploy Gemini Voice Agent</DialogTitle>
              <DialogDescription>
                Enter a phone number to deploy the Gemini voice agent. It will call to provide medication reminders and answer questions about your session.
              </DialogDescription>
            </DialogHeader>
            <div className="flex flex-col gap-3 py-4">
              <label htmlFor="phone-number" className="text-sm font-medium text-foreground">
                Phone Number
              </label>
              <input
                id="phone-number"
                type="tel"
                placeholder="+1 (555) 123-4567"
                value={phoneNumber}
                onChange={(e) => setPhoneNumber(e.target.value)}
                className="flex h-10 w-full rounded-md border border-border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              />
            </div>
            <DialogFooter className="gap-2">
              <DialogClose asChild>
                <button className="px-4 py-2 rounded-md border border-border text-sm font-medium hover:bg-muted transition-colors cursor-pointer">
                  Cancel
                </button>
              </DialogClose>
              <button
                disabled={!phoneNumber.trim() || deploying}
                onClick={async () => {
                  setDeploying(true)
                  setDeployError(null)
                  try {
                    const medsList = (runtimeMeds ?? [])
                      .filter((m: any) => m.name && m.name !== 'N/A')
                      .map((m: any) => `${m.name} (${m.dosage}) - ${m.purpose}`)
                      .join('\n')
                    const sessionSummary = [
                      summaryBullets.length > 0 ? 'Session Findings:\n' + summaryBullets.join('\n') : '',
                      medsList ? '\nDetected Medications:\n' + medsList : '',
                    ].filter(Boolean).join('\n') || 'No session summary available.'
                    const res = await fetch("http://localhost:8083/deploy-voice-agent", {
                      method: "POST",
                      headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({ phoneNumber: phoneNumber.trim(), sessionSummary }),
                    })
                    if (res.ok) {
                      setDeployed(true)
                      setPhoneDialogOpen(false)
                    } else {
                      const err = await res.json().catch(() => ({ error: `HTTP ${res.status}` }))
                      setDeployError(err.error || `Request failed (${res.status})`)
                    }
                  } catch (e: any) {
                    setDeployError(e.message || 'Network error — is the VAPI server running on port 8083?')
                  } finally {
                    setDeploying(false)
                  }
                }}
                className="px-4 py-2 rounded-md bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
              >
                {deploying ? "Deploying…" : "Deploy Agent"}
              </button>
              {deployError && (
                <p className="text-xs text-red-500 mt-2 col-span-full">{deployError}</p>
              )}
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </main>
    </div>
  )
}

function ActionCard({
  icon,
  title,
  description,
  disabled = false,
  onClick,
}: {
  icon: React.ReactNode
  title: string
  description: string
  disabled?: boolean
  onClick?: () => void
}) {
  return (
    <button
      disabled={disabled}
      onClick={onClick}
      className={`flex items-start gap-4 p-5 rounded-xl border text-left transition-all cursor-pointer ${
        disabled
          ? "border-border bg-muted opacity-50 cursor-not-allowed"
          : "border-border bg-card hover:shadow-md hover:border-primary/30"
      }`}
    >
      <div
        className={`flex items-center justify-center size-10 rounded-lg flex-shrink-0 ${
          disabled ? "bg-muted-foreground/10 text-muted-foreground" : "bg-primary/10 text-primary"
        }`}
      >
        {icon}
      </div>
      <div className="flex flex-col gap-1">
        <span className="text-sm font-semibold text-foreground">
          {title}
        </span>
        <span className="text-xs text-muted-foreground leading-relaxed">
          {description}
        </span>
        {disabled && (
          <span className="text-[10px] text-muted-foreground uppercase tracking-wider mt-1">
            Coming Soon
          </span>
        )}
      </div>
    </button>
  )
}

function GeminiIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M12 2C12 2 14.5 7.5 17.5 10.5C20.5 13.5 24 12 24 12C24 12 20.5 14.5 17.5 17.5C14.5 20.5 12 22 12 22C12 22 9.5 16.5 6.5 13.5C3.5 10.5 0 12 0 12C0 12 3.5 9.5 6.5 6.5C9.5 3.5 12 2 12 2Z"
        fill="currentColor"
      />
    </svg>
  )
}

function DeployVoiceAgentButton({ deployed, onClick }: { deployed: boolean; onClick: () => void }) {
  return (
    <button
      disabled={deployed}
      onClick={onClick}
      className={`mt-3 flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all cursor-pointer ${
        deployed
          ? "bg-primary/10 text-primary cursor-default"
          : "bg-primary/10 text-primary hover:bg-primary/20"
      }`}
    >
      <GeminiIcon className="size-3.5" />
      {deployed ? "Voice Agent Deployed ✓" : "Deploy Gemini Voice Agent"}
    </button>
  )
}
