"use client"

import {
  Mail,
  FileText,
  CalendarDays,
  ShoppingBag,
  Pill,
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  ArrowLeft,
  Clock,
} from "lucide-react"

const detectedMedications = [
  {
    name: "Metformin 500mg",
    type: "Biguanide",
    purpose: "Type 2 Diabetes",
    dosage: "500mg twice daily",
    status: "safe" as const,
  },
  {
    name: "Lisinopril 10mg",
    type: "ACE Inhibitor",
    purpose: "Hypertension",
    dosage: "10mg once daily",
    status: "safe" as const,
  },
  {
    name: "Atorvastatin 20mg",
    type: "Statin",
    purpose: "Cholesterol",
    dosage: "20mg at bedtime",
    status: "warning" as const,
  },
]

const interactionResults = [
  {
    pair: "Metformin + Lisinopril",
    severity: "none",
    note: "No known interaction. Safe to take together.",
  },
  {
    pair: "Metformin + Atorvastatin",
    severity: "none",
    note: "No known interaction. Safe to take together.",
  },
  {
    pair: "Lisinopril + Atorvastatin",
    severity: "mild",
    note: "Minor: Both may affect kidney function. Monitor with regular blood work.",
  },
]

const schedule = [
  { time: "8:00 AM", medications: ["Metformin 500mg", "Lisinopril 10mg"], meal: "With breakfast" },
  { time: "6:00 PM", medications: ["Metformin 500mg"], meal: "With dinner" },
  { time: "10:00 PM", medications: ["Atorvastatin 20mg"], meal: "Before bed" },
]

export function SummaryDashboard({ onBack }: { onBack: () => void }) {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-background/80 backdrop-blur-md border-b border-border">
        <div className="flex items-center justify-between px-6 py-4 max-w-5xl mx-auto">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
          >
            <ArrowLeft className="size-4" />
            New Session
          </button>
          <h1 className="text-sm font-semibold text-foreground">
            Session Summary
          </h1>
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Clock className="size-3.5" />
            <span>Feb 28, 2026</span>
          </div>
        </div>
      </header>

      <main className="px-6 py-8 max-w-5xl mx-auto flex flex-col gap-8">
        {/* AI Disclaimer */}
        <div className="flex items-start gap-3 p-4 rounded-xl border border-border bg-warning/10">
          <AlertTriangle className="size-5 text-warning-foreground flex-shrink-0 mt-0.5" />
          <p className="text-sm text-warning-foreground leading-relaxed">
            This summary was generated by an AI assistant and has not been reviewed by a medical professional. Always consult your doctor before making changes to your medication regimen.
          </p>
        </div>

        {/* Overall Safety Status */}
        <div className="flex flex-col items-center gap-3 p-8 rounded-2xl bg-primary/5 border border-primary/20">
          <div className="flex items-center justify-center size-16 rounded-full bg-primary/10">
            <ShieldCheck className="size-8 text-primary" />
          </div>
          <h2 className="text-xl font-bold text-foreground">
            No Critical Interactions Found
          </h2>
          <p className="text-sm text-muted-foreground text-center max-w-md">
            All 3 detected medications have been cross-checked against FDA databases. One minor note was flagged for your awareness.
          </p>
        </div>

        {/* Detected Medications */}
        <section className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <Pill className="size-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Detected Medications
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {detectedMedications.map((med) => (
              <div
                key={med.name}
                className="flex flex-col gap-3 p-5 rounded-xl border border-border bg-card"
              >
                <div className="flex items-start justify-between">
                  <div className="flex flex-col gap-1">
                    <h3 className="font-semibold text-foreground text-sm">
                      {med.name}
                    </h3>
                    <span className="text-xs text-muted-foreground">
                      {med.type}
                    </span>
                  </div>
                  {med.status === "safe" ? (
                    <CheckCircle2 className="size-5 text-success flex-shrink-0" />
                  ) : (
                    <AlertTriangle className="size-5 text-warning flex-shrink-0" />
                  )}
                </div>
                <div className="flex flex-col gap-1.5 text-xs text-muted-foreground">
                  <div className="flex items-center justify-between">
                    <span>Purpose</span>
                    <span className="text-foreground font-medium">{med.purpose}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Dosage</span>
                    <span className="text-foreground font-medium">{med.dosage}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Interaction Check */}
        <section className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <ShieldCheck className="size-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Interaction Check
            </h2>
          </div>
          <div className="flex flex-col gap-3">
            {interactionResults.map((result) => (
              <div
                key={result.pair}
                className="flex items-start gap-4 p-4 rounded-xl border border-border bg-card"
              >
                <div className="flex-shrink-0 mt-0.5">
                  {result.severity === "none" ? (
                    <CheckCircle2 className="size-5 text-success" />
                  ) : (
                    <AlertTriangle className="size-5 text-warning" />
                  )}
                </div>
                <div className="flex flex-col gap-1">
                  <h3 className="text-sm font-semibold text-foreground">
                    {result.pair}
                  </h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {result.note}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Medication Schedule */}
        <section className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <Clock className="size-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Recommended Schedule
            </h2>
          </div>
          <div className="flex flex-col gap-3">
            {schedule.map((slot) => (
              <div
                key={slot.time}
                className="flex items-center gap-5 p-4 rounded-xl border border-border bg-card"
              >
                <div className="flex flex-col items-center gap-0.5 min-w-[72px]">
                  <span className="text-base font-bold text-foreground">
                    {slot.time}
                  </span>
                  <span className="text-[10px] text-muted-foreground uppercase tracking-wider">
                    {slot.meal}
                  </span>
                </div>
                <div className="h-8 w-px bg-border" />
                <div className="flex flex-wrap gap-2">
                  {slot.medications.map((med) => (
                    <span
                      key={med}
                      className="px-3 py-1.5 rounded-lg bg-primary/10 text-primary text-xs font-medium"
                    >
                      {med}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Post-Session Actions */}
        <section className="flex flex-col gap-4">
          <h2 className="text-lg font-semibold text-foreground">
            Quick Actions
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <ActionCard
              icon={<Mail className="size-5" />}
              title="View Doctor's Draft"
              description="Open the prepared email summary for your physician"
            />
            <ActionCard
              icon={<FileText className="size-5" />}
              title="Share Schedule"
              description="Share the medication schedule as a Google Doc"
            />
            <ActionCard
              icon={<CalendarDays className="size-5" />}
              title="Add to Calendar"
              description="Sync dosage times to your Google Calendar"
            />
            <ActionCard
              icon={<ShoppingBag className="size-5" />}
              title="Order Refill"
              description="Connect to your pharmacy portal for refills"
              disabled
            />
          </div>
        </section>
      </main>
    </div>
  )
}

function ActionCard({
  icon,
  title,
  description,
  disabled = false,
}: {
  icon: React.ReactNode
  title: string
  description: string
  disabled?: boolean
}) {
  return (
    <button
      disabled={disabled}
      className={`flex items-start gap-4 p-5 rounded-xl border text-left transition-all cursor-pointer ${
        disabled
          ? "border-border bg-muted opacity-50 cursor-not-allowed"
          : "border-border bg-card hover:shadow-md hover:border-primary/30"
      }`}
    >
      <div
        className={`flex items-center justify-center size-10 rounded-lg flex-shrink-0 ${
          disabled ? "bg-muted-foreground/10 text-muted-foreground" : "bg-primary/10 text-primary"
        }`}
      >
        {icon}
      </div>
      <div className="flex flex-col gap-1">
        <span className="text-sm font-semibold text-foreground">
          {title}
        </span>
        <span className="text-xs text-muted-foreground leading-relaxed">
          {description}
        </span>
        {disabled && (
          <span className="text-[10px] text-muted-foreground uppercase tracking-wider mt-1">
            Coming Soon
          </span>
        )}
      </div>
    </button>
  )
}
